---
- hosts: all
  vars:
    home: /Users/bradleysheehan
    src_home: ~/Dev # Where your code lives
    applications: # .dmg, .app, .zip type applications via brew-cask
      - google-chrome
      - firefox
      - sublime-text

  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - curl
        - vim
        - ack
        - git
        - postgresql
        - phantomjs
        - redis
        - tmux

    - name: Setup launch agents for services
      command: launchctl load {{ home }}/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
      with_items:
        - postgresql

    - name: Check if Pow is installed
      stat: path={{ home }}/.pow
      register: pow_installed

    - name: Install Pow
      shell: curl get.pow.cx | sh
      when: pow_installed.stat.exists == false

    - name: Create src folder
      file: path={{ src_home }} state=directory

    - name: Check for installed apps
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: Install apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: item not in installed_applications.results|map(attribute='stdout')

    - name: install RVM
      shell: curl -L https://get.rvm.io | bash -s -- --ignore-dotfiles creates=~/.rvm
      tags: [ruby]

    - name: install base gems
      gem: name=$item state=present include_dependencies=False
      tags: [ruby]
      with_items:
        - algoplot
        - nokogiri
        - pry
        - pry-doc
        - rails